name: Build Kernel

on:
  workflow_dispatch:

jobs:
  build-kernel:
    name: Build Kernel
    runs-on: ubuntu-22.04
    steps:
      - name: Build
        uses: dabao1955/kernel_build_action@main
        with:
          kernel-url: https://github.com/ztc1997/android_gki_kernel_5.10_common
          kernel-branch: android12-5.10-2025-02
          config: gki_defconfig
          arch: arm64
          aosp-gcc: true
          aosp-clang: true
          lxc: true
          lxc-patch: true
          anykernel3: true
          android-version: 12
          aosp-clang-version: r383902
